# Generated by Django 2.2.12 on 2021-11-04 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interviews',
            new_name='Interview',
        ),
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
