# Generated by Django 2.2.12 on 2021-11-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
