# Generated by Django 2.2.12 on 2021-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211104_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
